/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/header-component/header-component.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './header-component.component.css.shim.ngstyle';
import * as import9 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import10 from '../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/router/src/directives/router_link';
import * as import16 from '@angular/router/src/directives/router_link_active';
export class Wrapper_HeaderComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HeaderComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.HeaderComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HeaderComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HeaderComponent>;
  _HeaderComponent_0_3:Wrapper_HeaderComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'header-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._HeaderComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HeaderComponentNgFactory:import7.ComponentFactory<import0.HeaderComponent> = new import7.ComponentFactory<import0.HeaderComponent>('header-component',View_HeaderComponent_Host0,import0.HeaderComponent);
const styles_HeaderComponent:any[] = [import8.styles];
var renderType_HeaderComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_HeaderComponent,{});
export class View_HeaderComponent0 extends import1.AppView<import0.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLink_12_3:import9.Wrapper_RouterLink;
  _RouterLinkActive_12_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_12_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_12_1:import11.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLink_15_3:import9.Wrapper_RouterLink;
  _RouterLinkActive_15_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_15_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import11.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLink_18_3:import9.Wrapper_RouterLink;
  _RouterLinkActive_18_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_18_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_18_1:import11.QueryList<any>;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _map_36:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent0,renderType_HeaderComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_36 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {exact: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'header-component works!',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','col-md-3 col-md-offset-3'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'button',new import3.InlineArray8(8,'class','btn btn-default','routerLink','','routerLinkActive','btn-danger','type','submit'),(null as any));
    this._RouterLink_12_3 = new import9.Wrapper_RouterLink(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_12_4 = new import10.Wrapper_RouterLinkActive(this.parentView.injectorGet(import12.Router,this.parentIndex),new import14.ElementRef(this._el_12),this.renderer,this.ref);
    this._query_RouterLink_12_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_12_1 = new import11.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'Button1',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'button',new import3.InlineArray8(8,'class','btn btn-primary','routerLink','binding','routerLinkActive','btn-danger','type','submit'),(null as any));
    this._RouterLink_15_3 = new import9.Wrapper_RouterLink(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_15_4 = new import10.Wrapper_RouterLinkActive(this.parentView.injectorGet(import12.Router,this.parentIndex),new import14.ElementRef(this._el_15),this.renderer,this.ref);
    this._query_RouterLink_15_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import11.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'Button2',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_10,'button',new import3.InlineArray8(8,'class','btn btn-primary','routerLink','datatable','routerLinkActive','btn-danger','type','submit'),(null as any));
    this._RouterLink_18_3 = new import9.Wrapper_RouterLink(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex));
    this._RouterLinkActive_18_4 = new import10.Wrapper_RouterLinkActive(this.parentView.injectorGet(import12.Router,this.parentIndex),new import14.ElementRef(this._el_18),this.renderer,this.ref);
    this._query_RouterLink_18_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_18_1 = new import11.QueryList<any>();
    this._text_19 = this.renderer.createText(this._el_18,'Button3',(null as any));
    this._text_20 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_8,'\n  ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.RouterLink) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLink_12_3.context; }
    if (((token === import16.RouterLinkActive) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkActive_12_4.context; }
    if (((token === import15.RouterLink) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLink_15_3.context; }
    if (((token === import16.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4.context; }
    if (((token === import15.RouterLink) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLink_18_3.context; }
    if (((token === import16.RouterLinkActive) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkActive_18_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = '';
    this._RouterLink_12_3.check_routerLink(currVal_12_0_0,throwOnChange,false);
    this._RouterLink_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_12_1_0:any = this._map_36(true);
    this._RouterLinkActive_12_4.check_routerLinkActiveOptions(currVal_12_1_0,throwOnChange,false);
    const currVal_12_1_1:any = 'btn-danger';
    this._RouterLinkActive_12_4.check_routerLinkActive(currVal_12_1_1,throwOnChange,false);
    this._RouterLinkActive_12_4.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_15_0_0:any = 'binding';
    this._RouterLink_15_3.check_routerLink(currVal_15_0_0,throwOnChange,false);
    this._RouterLink_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = 'btn-danger';
    this._RouterLinkActive_15_4.check_routerLinkActive(currVal_15_1_0,throwOnChange,false);
    this._RouterLinkActive_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_18_0_0:any = 'datatable';
    this._RouterLink_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLink_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_1_0:any = 'btn-danger';
    this._RouterLinkActive_18_4.check_routerLinkActive(currVal_18_1_0,throwOnChange,false);
    this._RouterLinkActive_18_4.ngDoCheck(this,this._el_18,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_12_0.dirty) {
        this._query_RouterLink_12_0.reset([this._RouterLink_12_3.context]);
        this._RouterLinkActive_12_4.context.links = this._query_RouterLink_12_0;
        this._query_RouterLink_12_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_12_1.dirty) {
        this._query_RouterLinkWithHref_12_1.reset(([] as any[]));
        this._RouterLinkActive_12_4.context.linksWithHrefs = this._query_RouterLinkWithHref_12_1;
        this._query_RouterLinkWithHref_12_1.notifyOnChanges();
      }
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset([this._RouterLink_15_3.context]);
        this._RouterLinkActive_15_4.context.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset(([] as any[]));
        this._RouterLinkActive_15_4.context.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if (this._query_RouterLink_18_0.dirty) {
        this._query_RouterLink_18_0.reset([this._RouterLink_18_3.context]);
        this._RouterLinkActive_18_4.context.links = this._query_RouterLink_18_0;
        this._query_RouterLink_18_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_18_1.dirty) {
        this._query_RouterLinkWithHref_18_1.reset(([] as any[]));
        this._RouterLinkActive_18_4.context.linksWithHrefs = this._query_RouterLinkWithHref_18_1;
        this._query_RouterLinkWithHref_18_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_12_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_18_4.context.ngAfterContentInit(); }
    }
  }
  destroyInternal():void {
    this._RouterLinkActive_12_4.ngOnDestroy();
    this._RouterLinkActive_15_4.ngOnDestroy();
    this._RouterLinkActive_18_4.ngOnDestroy();
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_12_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_15_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
}