/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['.nav-sidebar[_ngcontent-%COMP%] {\n  margin-right: -21px; \n  margin-bottom: 20px;\n  margin-left: -20px;\n}\n.nav-sidebar[_ngcontent-%COMP%]    > li[_ngcontent-%COMP%]    > a[_ngcontent-%COMP%] {\n  padding-right: 20px;\n  padding-left: 20px;\n}\n.nav-sidebar[_ngcontent-%COMP%]    > .active[_ngcontent-%COMP%]    > a[_ngcontent-%COMP%], .nav-sidebar[_ngcontent-%COMP%]    > .active[_ngcontent-%COMP%]    > a[_ngcontent-%COMP%]:hover, .nav-sidebar[_ngcontent-%COMP%]    > .active[_ngcontent-%COMP%]    > a[_ngcontent-%COMP%]:focus {\n  color: #fff;\n  background-color: #428bca;\n}'];
//# sourceMappingURL=left-menu-component.component.css.shim.ngstyle.js.map