/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/left-menu-component/left-menu-component.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './left-menu-component.component.css.shim.ngstyle';
export class Wrapper_LeftMenuComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LeftMenuComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.LeftMenuComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LeftMenuComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LeftMenuComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LeftMenuComponent>;
  _LeftMenuComponent_0_3:Wrapper_LeftMenuComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LeftMenuComponent_Host0,renderType_LeftMenuComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'left-menu-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LeftMenuComponent0(this.viewUtils,this,0,this._el_0);
    this._LeftMenuComponent_0_3 = new Wrapper_LeftMenuComponent();
    this.compView_0.create(this._LeftMenuComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LeftMenuComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LeftMenuComponent) && (0 === requestNodeIndex))) { return this._LeftMenuComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LeftMenuComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LeftMenuComponentNgFactory:import7.ComponentFactory<import0.LeftMenuComponent> = new import7.ComponentFactory<import0.LeftMenuComponent>('left-menu-component',View_LeftMenuComponent_Host0,import0.LeftMenuComponent);
const styles_LeftMenuComponent:any[] = [import8.styles];
var renderType_LeftMenuComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_LeftMenuComponent,{});
export class View_LeftMenuComponent0 extends import1.AppView<import0.LeftMenuComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LeftMenuComponent0,renderType_LeftMenuComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','sidebar'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','nav nav-sidebar'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'li',new import3.InlineArray2(2,'class','active'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Overview ',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_2,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Reports',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_12,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Analytics',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_2,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Export',(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','nav nav-sidebar'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_23,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Nav item',(null as any));
    this._text_26 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_21,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Nav item again',(null as any));
    this._text_30 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_21,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_31,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'One more nav',(null as any));
    this._text_34 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_21,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_35,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Another nav item',(null as any));
    this._text_38 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_21,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_39,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'More navigation',(null as any));
    this._text_42 = this.renderer.createText(this._el_21,'\n  ',(null as any));
    this._text_43 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','nav nav-sidebar'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n    ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_44,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_46,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Nav item again',(null as any));
    this._text_49 = this.renderer.createText(this._el_44,'\n    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_44,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_50,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'One more nav',(null as any));
    this._text_53 = this.renderer.createText(this._el_44,'\n    ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_44,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_54,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'Another nav item',(null as any));
    this._text_57 = this.renderer.createText(this._el_44,'\n  ',(null as any));
    this._text_58 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_59 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59
    ]
    ),(null as any));
    return (null as any);
  }
}