/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../src/app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './app.component.css.shim.ngstyle';
import * as import9 from '../../../src/app/header-component/header-component.component';
import * as import10 from './header-component/header-component.component.ngfactory';
import * as import11 from '../../../src/app/left-menu-component/left-menu-component.component';
import * as import12 from './left-menu-component/left-menu-component.component.ngfactory';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import15 from '@angular/router/src/router_outlet_map';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
import * as import17 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-root',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('app-root',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import8.styles];
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_4_3:import10.Wrapper_HeaderComponent;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  compView_11:import1.AppView<import11.LeftMenuComponent>;
  _LeftMenuComponent_11_3:import12.Wrapper_LeftMenuComponent;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _vc_16:import13.ViewContainer;
  _RouterOutlet_16_5:import14.Wrapper_RouterOutlet;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'header-component',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import10.View_HeaderComponent0(this.viewUtils,this,4,this._el_4);
    this._HeaderComponent_4_3 = new import10.Wrapper_HeaderComponent();
    this.compView_4.create(this._HeaderComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','col-md-2 col-sm-3 sidebar'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'left-menu-component',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_11 = new import12.View_LeftMenuComponent0(this.viewUtils,this,11,this._el_11);
    this._LeftMenuComponent_11_3 = new import12.Wrapper_LeftMenuComponent();
    this.compView_11.create(this._LeftMenuComponent_11_3.context);
    this._text_12 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','col-md-10 col-sm-3'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_16 = new import13.ViewContainer(16,14,this,this._el_16);
    this._RouterOutlet_16_5 = new import14.Wrapper_RouterOutlet(this.parentView.injectorGet(import15.RouterOutletMap,this.parentIndex),this._vc_16.vcRef,this.parentView.injectorGet(import16.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_17 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (4 === requestNodeIndex))) { return this._HeaderComponent_4_3.context; }
    if (((token === import11.LeftMenuComponent) && (11 === requestNodeIndex))) { return this._LeftMenuComponent_11_3.context; }
    if (((token === import17.RouterOutlet) && (16 === requestNodeIndex))) { return this._RouterOutlet_16_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._LeftMenuComponent_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    this._RouterOutlet_16_5.ngDoCheck(this,this._el_16,throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this.compView_4.internalDetectChanges(throwOnChange);
    this.compView_11.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_16.destroyNestedViews();
    this.compView_4.destroy();
    this.compView_11.destroy();
    this._RouterOutlet_16_5.ngOnDestroy();
  }
}