/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.datatable[_ngcontent-%COMP%] {\n  text-align: left;\n  width:75%;\n  margin:0 auto;\n}'];