/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/binding/binding.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '../../../../src/app/service/userdata.service';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from './binding.component.css.shim.ngstyle';
import * as import12 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import13 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import14 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import16 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_name.ngfactory';
import * as import17 from '@angular/core/src/change_detection/change_detection_util';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/forms/src/directives/default_value_accessor';
import * as import20 from '@angular/forms/src/directives/control_value_accessor';
import * as import21 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/ng_control_status';
import * as import24 from '@angular/forms/src/directives/reactive_directives/form_group_name';
import * as import25 from '@angular/forms/src/directives/control_container';
import * as import26 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
export class Wrapper_BindingComponent {
  /*private*/ _eventHandler:Function;
  context:import0.BindingComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.BindingComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_BindingComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_BindingComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.BindingComponent>;
  _BindingComponent_0_3:Wrapper_BindingComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BindingComponent_Host0,renderType_BindingComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-binding',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_BindingComponent0(this.viewUtils,this,0,this._el_0);
    this._BindingComponent_0_3 = new Wrapper_BindingComponent(this.injectorGet(import8.ActivatedRoute,this.parentIndex),this.injectorGet(import9.UserdataService,this.parentIndex),this.injectorGet(import10.FormBuilder,this.parentIndex));
    this.compView_0.create(this._BindingComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._BindingComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.BindingComponent) && (0 === requestNodeIndex))) { return this._BindingComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._BindingComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const BindingComponentNgFactory:import7.ComponentFactory<import0.BindingComponent> = new import7.ComponentFactory<import0.BindingComponent>('app-binding',View_BindingComponent_Host0,import0.BindingComponent);
const styles_BindingComponent:any[] = [import11.styles];
var renderType_BindingComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_BindingComponent,{});
export class View_BindingComponent0 extends import1.AppView<import0.BindingComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _FormGroupDirective_3_3:import12.Wrapper_FormGroupDirective;
  _ControlContainer_3_4:any;
  _NgControlStatusGroup_3_5:import13.Wrapper_NgControlStatusGroup;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _DefaultValueAccessor_9_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_9_4:any[];
  _FormControlName_9_5:import15.Wrapper_FormControlName;
  _NgControl_9_6:any;
  _NgControlStatus_9_7:import13.Wrapper_NgControlStatus;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_17_4:any[];
  _FormControlName_17_5:import15.Wrapper_FormControlName;
  _NgControl_17_6:any;
  _NgControlStatus_17_7:import13.Wrapper_NgControlStatus;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_25_4:any[];
  _FormControlName_25_5:import15.Wrapper_FormControlName;
  _NgControl_25_6:any;
  _NgControlStatus_25_7:import13.Wrapper_NgControlStatus;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _FormGroupName_29_3:import16.Wrapper_FormGroupName;
  _ControlContainer_29_4:any;
  _NgControlStatusGroup_29_5:import13.Wrapper_NgControlStatusGroup;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _DefaultValueAccessor_35_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_35_4:any[];
  _FormControlName_35_5:import15.Wrapper_FormControlName;
  _NgControl_35_6:any;
  _NgControlStatus_35_7:import13.Wrapper_NgControlStatus;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _DefaultValueAccessor_43_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_43_4:any[];
  _FormControlName_43_5:import15.Wrapper_FormControlName;
  _NgControl_43_6:any;
  _NgControlStatus_43_7:import13.Wrapper_NgControlStatus;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  /*private*/ _expr_83:any;
  /*private*/ _expr_84:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BindingComponent0,renderType_BindingComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_83 = import17.UNINITIALIZED;
    this._expr_84 = import17.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'form',new import3.InlineArray2(2,'novalidate',''),(null as any));
    this._FormGroupDirective_3_3 = new import12.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_3_4 = this._FormGroupDirective_3_3.context;
    this._NgControlStatusGroup_3_5 = new import13.Wrapper_NgControlStatusGroup(this._ControlContainer_3_4);
    this._text_4 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'label',new import3.InlineArray2(2,'class','center-block'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Name:\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray4(4,'class','form-control','formControlName','name'),(null as any));
    this._DefaultValueAccessor_9_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_9));
    this._NG_VALUE_ACCESSOR_9_4 = [this._DefaultValueAccessor_9_3.context];
    this._FormControlName_9_5 = new import15.Wrapper_FormControlName(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_4);
    this._NgControl_9_6 = this._FormControlName_9_5.context;
    this._NgControlStatus_9_7 = new import13.Wrapper_NgControlStatus(this._NgControl_9_6);
    this._text_10 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._text_12 = this.renderer.createText(this._el_3,'\n\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'label',new import3.InlineArray2(2,'class','center-block'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Gender:\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'input',new import3.InlineArray4(4,'class','form-control','formControlName','gender'),(null as any));
    this._DefaultValueAccessor_17_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_17));
    this._NG_VALUE_ACCESSOR_17_4 = [this._DefaultValueAccessor_17_3.context];
    this._FormControlName_17_5 = new import15.Wrapper_FormControlName(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_17_4);
    this._NgControl_17_6 = this._FormControlName_17_5.context;
    this._NgControlStatus_17_7 = new import13.Wrapper_NgControlStatus(this._NgControl_17_6);
    this._text_18 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_20 = this.renderer.createText(this._el_3,'\n\n  ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'label',new import3.InlineArray2(2,'class','center-block'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Age:\n      ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'input',new import3.InlineArray4(4,'class','form-control','formControlName','age'),(null as any));
    this._DefaultValueAccessor_25_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_25));
    this._NG_VALUE_ACCESSOR_25_4 = [this._DefaultValueAccessor_25_3.context];
    this._FormControlName_25_5 = new import15.Wrapper_FormControlName(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_4);
    this._NgControl_25_6 = this._FormControlName_25_5.context;
    this._NgControlStatus_25_7 = new import13.Wrapper_NgControlStatus(this._NgControl_25_6);
    this._text_26 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_21,'\n  ',(null as any));
    this._text_28 = this.renderer.createText(this._el_3,'\n\n  ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'formGroupName','address'),(null as any));
    this._FormGroupName_29_3 = new import16.Wrapper_FormGroupName(this._ControlContainer_3_4,(null as any),(null as any));
    this._ControlContainer_29_4 = this._FormGroupName_29_3.context;
    this._NgControlStatusGroup_29_5 = new import13.Wrapper_NgControlStatusGroup(this._ControlContainer_29_4);
    this._text_30 = this.renderer.createText(this._el_29,'\n    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'label',new import3.InlineArray2(2,'class','center-block'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'State:\n        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'input',new import3.InlineArray4(4,'class','form-control','formControlName','state'),(null as any));
    this._DefaultValueAccessor_35_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_35));
    this._NG_VALUE_ACCESSOR_35_4 = [this._DefaultValueAccessor_35_3.context];
    this._FormControlName_35_5 = new import15.Wrapper_FormControlName(this._ControlContainer_29_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_35_4);
    this._NgControl_35_6 = this._FormControlName_35_5.context;
    this._NgControlStatus_35_7 = new import13.Wrapper_NgControlStatus(this._NgControl_35_6);
    this._text_36 = this.renderer.createText(this._el_33,'\n      ',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_29,'\n\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_29,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'label',new import3.InlineArray2(2,'class','center-block'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'City:\n        ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_41,'input',new import3.InlineArray4(4,'class','form-control','formControlName','city'),(null as any));
    this._DefaultValueAccessor_43_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_43));
    this._NG_VALUE_ACCESSOR_43_4 = [this._DefaultValueAccessor_43_3.context];
    this._FormControlName_43_5 = new import15.Wrapper_FormControlName(this._ControlContainer_29_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_43_4);
    this._NgControl_43_6 = this._FormControlName_43_5.context;
    this._NgControlStatus_43_7 = new import13.Wrapper_NgControlStatus(this._NgControl_43_6);
    this._text_44 = this.renderer.createText(this._el_41,'\n      ',(null as any));
    this._text_45 = this.renderer.createText(this._el_39,'\n    ',(null as any));
    this._text_46 = this.renderer.createText(this._el_29,'\n  ',(null as any));
    this._text_47 = this.renderer.createText(this._el_3,'\n\n  ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray4(4,'class','btn btn-success','type','submit'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Save',(null as any));
    this._text_50 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_51 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_3));
    this._FormGroupDirective_3_3.subscribe(this,this.eventHandler(this.handleEvent_3),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_25));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_35,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_35));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_43,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_43));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (9 === requestNodeIndex))) { return this._DefaultValueAccessor_9_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_4; }
    if (((token === import21.FormControlName) && (9 === requestNodeIndex))) { return this._FormControlName_9_5.context; }
    if (((token === import22.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_6; }
    if (((token === import23.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_7.context; }
    if (((token === import19.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_4; }
    if (((token === import21.FormControlName) && (17 === requestNodeIndex))) { return this._FormControlName_17_5.context; }
    if (((token === import22.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_6; }
    if (((token === import23.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_7.context; }
    if (((token === import19.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_4; }
    if (((token === import21.FormControlName) && (25 === requestNodeIndex))) { return this._FormControlName_25_5.context; }
    if (((token === import22.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_6; }
    if (((token === import23.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_7.context; }
    if (((token === import19.DefaultValueAccessor) && (35 === requestNodeIndex))) { return this._DefaultValueAccessor_35_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (35 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_35_4; }
    if (((token === import21.FormControlName) && (35 === requestNodeIndex))) { return this._FormControlName_35_5.context; }
    if (((token === import22.NgControl) && (35 === requestNodeIndex))) { return this._NgControl_35_6; }
    if (((token === import23.NgControlStatus) && (35 === requestNodeIndex))) { return this._NgControlStatus_35_7.context; }
    if (((token === import19.DefaultValueAccessor) && (43 === requestNodeIndex))) { return this._DefaultValueAccessor_43_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (43 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_43_4; }
    if (((token === import21.FormControlName) && (43 === requestNodeIndex))) { return this._FormControlName_43_5.context; }
    if (((token === import22.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_6; }
    if (((token === import23.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_7.context; }
    if (((token === import24.FormGroupName) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._FormGroupName_29_3.context; }
    if (((token === import25.ControlContainer) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ControlContainer_29_4; }
    if (((token === import23.NgControlStatusGroup) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgControlStatusGroup_29_5.context; }
    if (((token === import26.FormGroupDirective) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._FormGroupDirective_3_3.context; }
    if (((token === import25.ControlContainer) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._ControlContainer_3_4; }
    if (((token === import23.NgControlStatusGroup) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgControlStatusGroup_3_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.context.myForm;
    this._FormGroupDirective_3_3.check_form(currVal_3_0_0,throwOnChange,false);
    this._FormGroupDirective_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this._NgControlStatusGroup_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    this._DefaultValueAccessor_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = 'name';
    this._FormControlName_9_5.check_name(currVal_9_1_0,throwOnChange,false);
    this._FormControlName_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_7.ngDoCheck(this,this._el_9,throwOnChange);
    this._DefaultValueAccessor_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_17_1_0:any = 'gender';
    this._FormControlName_17_5.check_name(currVal_17_1_0,throwOnChange,false);
    this._FormControlName_17_5.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatus_17_7.ngDoCheck(this,this._el_17,throwOnChange);
    this._DefaultValueAccessor_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    const currVal_25_1_0:any = 'age';
    this._FormControlName_25_5.check_name(currVal_25_1_0,throwOnChange,false);
    this._FormControlName_25_5.ngDoCheck(this,this._el_25,throwOnChange);
    this._NgControlStatus_25_7.ngDoCheck(this,this._el_25,throwOnChange);
    const currVal_29_0_0:any = 'address';
    this._FormGroupName_29_3.check_name(currVal_29_0_0,throwOnChange,false);
    this._FormGroupName_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    this._NgControlStatusGroup_29_5.ngDoCheck(this,this._el_29,throwOnChange);
    this._DefaultValueAccessor_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_35_1_0:any = 'state';
    this._FormControlName_35_5.check_name(currVal_35_1_0,throwOnChange,false);
    this._FormControlName_35_5.ngDoCheck(this,this._el_35,throwOnChange);
    this._NgControlStatus_35_7.ngDoCheck(this,this._el_35,throwOnChange);
    this._DefaultValueAccessor_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_43_1_0:any = 'city';
    this._FormControlName_43_5.check_name(currVal_43_1_0,throwOnChange,false);
    this._FormControlName_43_5.ngDoCheck(this,this._el_43,throwOnChange);
    this._NgControlStatus_43_7.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_83:any = import3.inlineInterpolate(1,'',((this.context.person == null)? (null as any): this.context.person.name),'');
    if (import3.checkBinding(throwOnChange,this._expr_83,currVal_83)) {
      this.renderer.setText(this._text_1,currVal_83);
      this._expr_83 = currVal_83;
    }
    this._NgControlStatusGroup_3_5.checkHost(this,this,this._el_3,throwOnChange);
    this._NgControlStatus_9_7.checkHost(this,this,this._el_9,throwOnChange);
    this._NgControlStatus_17_7.checkHost(this,this,this._el_17,throwOnChange);
    this._NgControlStatus_25_7.checkHost(this,this,this._el_25,throwOnChange);
    this._NgControlStatusGroup_29_5.checkHost(this,this,this._el_29,throwOnChange);
    this._NgControlStatus_35_7.checkHost(this,this,this._el_35,throwOnChange);
    this._NgControlStatus_43_7.checkHost(this,this,this._el_43,throwOnChange);
    const currVal_84:any = this.context.myForm.pristine;
    if (import3.checkBinding(throwOnChange,this._expr_84,currVal_84)) {
      this.renderer.setElementProperty(this._el_48,'disabled',currVal_84);
      this._expr_84 = currVal_84;
    }
  }
  destroyInternal():void {
    this._FormControlName_9_5.ngOnDestroy();
    this._FormControlName_17_5.ngOnDestroy();
    this._FormControlName_25_5.ngOnDestroy();
    this._FormControlName_35_5.ngOnDestroy();
    this._FormControlName_43_5.ngOnDestroy();
    this._FormGroupName_29_3.ngOnDestroy();
    this._FormGroupDirective_3_3.ngOnDestroy();
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_3_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_9_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_17_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_25_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_35(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_35_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_43(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_43_3.handleEvent(eventName,$event) && result);
    return result;
  }
}